import * as enums from './destinyEnums';
import manifest from './manifest';

export function talentGridNodeStepDefinition(talentGridHash, nodeStepHash) {
  const definitionTalentGrid = manifest.DestinyTalentGridDefinition[talentGridHash];

  const node = definitionTalentGrid.nodes.find((node) => node.steps.find((step) => step.nodeStepHash === +nodeStepHash));

  return node?.steps?.[0] || false;
}

const SUBCLASS_PATH_IDENTIFIERS = { First: 'FirstPath', Second: 'SecondPath', Third: 'ThirdPath' };

export const SUBCLASS_PATHS = [
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 4099943028,
    icon: '',
    art: '01A3-0000112B.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 4293830764,
    icon: '',
    art: '01A3-0000112B.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 2795355746,
    icon: '',
    art: '01E3-00001598.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 3928207649,
    icon: '',
    art: '01A3-0000116E.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 1236431642,
    icon: '',
    art: '01A3-0000116E.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 1323416107,
    icon: '',
    art: '01E3-0000159D.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 3806272138,
    icon: '',
    art: '01A3-00001179.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 1347995538,
    icon: '',
    art: '01A3-00001179.png',
  },
  {
    classType: enums.DestinyClass.Titan,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 3504292102,
    icon: '',
    art: '01E3-0000159F.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 1690891826,
    icon: '',
    art: '01A3-000010B4.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 313617030,
    icon: '',
    art: '01A3-000010B4.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 3006627468,
    icon: '',
    art: '01E3-00001593.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 2242504056,
    icon: '',
    art: '01A3-000010F8.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 2805396803,
    icon: '',
    art: '01A3-000010F8.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 1590824323,
    icon: '',
    art: '01E3-00001595.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 277476372,
    icon: '',
    art: '01A3-00001107.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 4025960910,
    icon: '',
    art: '01A3-00001107.png',
  },
  {
    classType: enums.DestinyClass.Hunter,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 499823166,
    icon: '',
    art: '01E3-00001596.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 487158888,
    icon: '',
    art: '01A3-000011A1.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 3297679786,
    icon: '',
    art: '01A3-000011A1.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Arc,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 3882393894,
    icon: '',
    art: '01E3-000015A1.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 1893159641,
    icon: '',
    art: '01A3-000011F1.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 966868917,
    icon: '',
    art: '01A3-000011F1.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Solar,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 935376049,
    icon: '',
    art: '01E3-000015A2.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.First,
    nodeStepHash: 2718724912,
    icon: '',
    art: '01A3-0000120D.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Second,
    nodeStepHash: 1389184794,
    icon: '',
    art: '01A3-0000120D.png',
  },
  {
    classType: enums.DestinyClass.Warlock,
    damageType: enums.DestinyDamageType.Void,
    identifier: SUBCLASS_PATH_IDENTIFIERS.Third,
    nodeStepHash: 194702279,
    icon: '',
    art: '01E3-000015A5.png',
  },
];
